const GET_DOGS = "GET_DOGS";
const CHANGE_PAGE = "CHANGE_PAGE";
const BY_NAME = "BY_NAME";
const BY_ID = "BY_ID";
const GET_TEMPS = "GET_TEMPS";
const FILTER = "FILTER";
const SORT_DOGS = "SORT_DOGS";
const CREATE_DOG = "CREATE_DOG";

export {
  GET_DOGS,
  CHANGE_PAGE,
  BY_NAME,
  BY_ID,
  FILTER,
  GET_TEMPS,
  SORT_DOGS,
  CREATE_DOG,
};
